[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.cloudfront.net *.netlify.com; img-src 'self' data: blob: *.cloudfront.net; connect-src 'self' *.netlify.com;" 